spring:
  datasource:
    url: jdbc:postgresql://localhost:${DB_PORT:5432}/${DB_NAME:vantrack_db}
    username: ${DB_USER}
    password: ${DB_PASS}
  jpa:
    show-sql: true

logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.springframework.security: TRACE

app:
  cors:
    allowed-origins: "*"