### Admin Login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "admin@vantrack.com",
  "password": "admin123"
}
> {%
    let token = response.body;

    client.global.set("authToken", token)
    console.log("Token gerado com sucesso!");
  %}

### Driver Login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "driver2@vantrack.com",
  "password": "secret123"
}
> {%
    let token = response.body;

    client.global.set("authTokenDriver", token)
    console.log("Token do usuário driver gerado com sucesso!");
%}
