### Create Route
POST {{baseUrl}}/routes
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "name": "EE Jose Maria - Tarde",
  "vanId": "e64d930e-2e0e-48cc-9c8c-1e219bbaf6ed"
}

### Find All Routes
GET {{baseUrl}}/routes
Content-Type: application/json
Authorization: Bearer {{authToken}}
