### Create Route
POST {{baseUrl}}/routes
Content-Type: application/json
Authorization: Bearer {{authTokenDriver}}

{
  "name": "EE Jose Maria - Tarde",
  "vanId": "1052b0fc-5314-4f8f-89ab-5b53bef7cf42"
}

### Find All Routes
GET {{baseUrl}}/routes
Content-Type: application/json
Authorization: Bearer {{authToken}}
