### Create Van
POST {{baseUrl}}/vans
Content-Type: application/json
Authorization: Bearer {{authTokenDriver}}

{
  "driverId": "7b3bd226-a601-4826-a911-ab09592dc873",
  "plate": "PWY3A22"
}

### Find All Vans
GET {{baseUrl}}/vans
Content-Type: application/json
Authorization: Bearer {{authToken}}
