### Create Van
POST {{baseUrl}}/vans
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "driverId": "31ea494e-2d08-437a-9d13-cb921db68795",
  "plate": "OAS1SWW"
}

### Find All Vans
GET {{baseUrl}}/vans
Content-Type: application/json
Authorization: Bearer {{authToken}}
