### Create Van
POST {{baseUrl}}/vans
Content-Type: application/json
Authorization: Bearer {{authTokenDriver}}

{
  "driverId": "4034d14b-03ac-40e3-aba4-71950283e852",
  "plate": "OPH1221"
}

### Find All Vans
GET {{baseUrl}}/vans
Content-Type: application/json
Authorization: Bearer {{authToken}}
